### ISSUE TITLE
Utilize AWS_REGION and AWS_DEFAULT_REGION environment variables when provisioning

### ISSUE THREAD

**Issue by ethanholz** [omsf-eco-infra/gha-runner#26]
When using `configure-aws-credientials`, `AWS_REGION` and `AWS_DEFAULT_REGION` get set in the environment and passed down to our container. The `AWS_REGION` gets populated by the region that is set during setup. Utilizing the variables reduces redundancy in our configs and will get automatically picked up by `boto3` (similar to how we currently get the keys from the environment). Adopting these as practice allows for us to stay in line with AWS best practices when utilizing the SDK.

Furthermore, this would reduce the start and stop to look like the following.

**Start**
```yaml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <your-IAM-Role-ARN>
          aws-region: <your-region-here, for example us-east-1>
      - name: Create cloud runner
        id: aws-start
        uses: omsf-eco-infra/gha-runner@v0.2.0
        with:
          provider: "aws"
          action: "start"
          aws_image_id: <your-ami-here, for example ami-0d5079d9be06933e5>
          aws_instance_type: <your instance type here, for example g4dn.xlarge>
          aws_home_dir: /home/ubuntu
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
```

**Stop**
```yaml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <your-IAM-Role-ARN>
          aws-region: <your-region-here, for example us-east-1>
      - name: Stop instances
        uses: omsf-eco-infra/gha-runner@v0.2.0
        with:
          provider: "aws"
          action: "stop"
          instance_mapping: ${{ needs.start-aws-runner.outputs.mapping }}
 ```
